# Generated by Django 4.1.3 on 2023-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('USA', 'USA')], default='AU', max_length=3),
        ),
        migrations.AddField(
            model_name='university',
            name='state',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
