# Generated by Django 4.1.3 on 2023-09-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_discussioncomment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussioncomment',
            name='user',
        ),
    ]
